default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  port: 5432
  username: rails
  password: rails

development:
  <<: *default
  database: cognos_vault_development

test:
  <<: *default
  database: cognos_vault_test

production:
  <<: *default
  database: cognos_vault_production
