source "https://rubygems.org"

ruby "3.3.0"

gem "rails", "~> 7.1.3"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
# gem "rack-cors"

group :development, :test do
  gem "pry"
  gem "mailcatcher"
  gem "rspec-rails"
  gem "factory_bot_rails"
  gem "faker"
end
